### ISSUE TITLE
fatal error: 'Zend/zend_smart_str.h' file not found

### ISSUE THREAD

**Issue by victor-sudakov** [simplerezo/freebsd-ports-php56#3]
A number of php56 extensions fail to build with the 'fatal error: 'Zend/zend_smart_str.h' file not found' error. Probably some important Zend dependency or library has been removed from the current ports tree. 

I'm attaching a typical poudriere log if you are interested.

[php56-pecl-memcached-3.1.5.log](https://github.com/simplerezo/freebsd-ports-php56/files/5813670/php56-pecl-memcached-3.1.5.log)

**Comment by mariancerny** [comment]
I can confirm that there is the same issue in "my" version of freebsd-ports-php56 (https://github.com/mariancerny/freebsd-ports-php56).
I personally don't need pecl-memcached and I don't have time to debug this issue, so I can't help you, sorry.
